export const APP_NAMES = {
  HOME: 'rnps-home',
  PS_STORE: 'rnps-store',
  PS_PLUS: 'rnps-plus',
  PS_PLUS_SVC_HUB: 'psplus-service-hub',
  ACTION_CARD_HOST: 'action-card-host-app',
  CONTROL_CENTER: 'control-center',
  CAPTURE_MENU: 'rnps-capture-menu',
  GAME_HUB: 'game-hub',
  BIG_APP_COMP: 'bigappcompanion',
  MONTE_CARLO: 'monte-carlo',
  SCREEN_SHARE: 'screen-share',
  PROFILE: 'profile',
  UNIVERSAL_CHECKOUT: 'universal-checkout',
  LIBRARY: 'rnps-library',
  EXPLORE_HUB: 'explore-hub',
  SETTINGS: 'settings',
  TROPHY: 'rnps-trophy',
  MF: 'mf',
  BGFT: 'BGFT',
  GAMING_LOUNGE: 'gaming-lounge',
  STORE: 'elysion',
  IGC: 'igc-browse',
  AUTO_SIGN_IN: 'auto-sign-in',
  SEARCH: 'rnps-search',
  MEDIA_GALLRY: 'rnps-media-gallery',
  REMOTE_PLAY_HUB: 'rnps-remoteplay-hub',
  MODAL_DIALOG: 'system-modal-dialog',
  NOTIFICATION_OVERLAY: 'notification-overlay',
  WEB_LAUNCHER: 'rnps-web-launcher',
};
type APPS_DATA = {
  [key: string]: { icon: string; abrv: string };
};
export const APPS: APPS_DATA = {
  'rnps-home': { icon: '🏠', abrv: 'HOME' },
  'rnps-store': { icon: '🛒', abrv: 'STORE' },
  'rnps-plus': { icon: '➕', abrv: 'PLUS' },
  'psplus-service-hub': { icon: '➕', abrv: 'PLUS SVC' },
  'action-card-host-app': { icon: '🃏', abrv: 'CARD' },
  'control-center': { icon: '🎛️', abrv: 'CC' },
  'rnps-capture-menu': { icon: '📸', abrv: 'CAPTURE' },
  'game-hub': { icon: '👾', abrv: 'GH' },
  bigappcompanion: { icon: '🐰', abrv: 'BAC' },
  'monte-carlo': { icon: '📺', abrv: 'VIDEO' },
  'screen-share': { icon: '🖥️', abrv: 'SHARE' },
  profile: { icon: '👤', abrv: 'PROF' },
  'universal-checkout': { icon: '💳', abrv: 'UC' },
  'rnps-library': { icon: '📚', abrv: 'LIB' },
  'explore-hub': { icon: '🔦', abrv: 'EXP' },
  settings: { icon: '⚙️', abrv: 'SET' },
  'rnps-trophy': { icon: '🏆', abrv: 'TROPHY' },
  mf: { icon: '🙂', abrv: 'MF' },
  BGFT: { icon: '⤵️', abrv: 'BGFT' },
  'gaming-lounge': { icon: '💺', abrv: 'LOUNGE' },
  elysion: { icon: '🛒', abrv: 'STORE' },
  'igc-browse': { icon: '🪙', abrv: 'IGC' },
  'auto-sign-in': { icon: '🔑', abrv: 'AUTO' },
  'rnps-search': { icon: '🔍', abrv: 'SEARCH' },
  'rnps-media-gallery': { icon: '🏞️', abrv: 'MEDIA' },
  'rnps-remoteplay-hub': { icon: '📲', abrv: 'REMOTE' },
  'system-modal-dialog': { icon: '💻', abrv: 'SYSTEM' },
  'notification-overlay': { icon: '🔔', abrv: 'NOTIF' },
  'rnps-web-launcher': { icon: '🌐', abrv: 'WEB' },
  default: { icon: '⚪️', abrv: 'APP' },
};
export const getAppIcon = (appName: string | undefined) => {
  const app = APPS[appName ?? 'default'];
  return app ? app.icon : APPS.default.icon;
};
